version: "3.9"
services:
  # postgres:
  #   image: postgres:13.1
  #   container_name: postgres
  #   volumes:
  #     - /tmp/postgres_argo_cd_demo/:/var/lib/postgresql/data
  #   #   - ${PWD}/db/:/tmp/
  #   ports:
  #     - "5432:5432"
  #   restart: always
  #   environment:
  #     POSTGRES_USER: argo
  #     POSTGRES_DB: argo
  #     POSTGRES_PASSWORD: argo
  #   # command: postgres -c 'max_connections=10'
  #   networks:
  #     - test
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8090:8080
  #   networks:
  #     - test
  backend:
   #image: ghcr.io/modulus/user-rust:latest
   build: .
   container_name: backend
   ports:
     - "5000:8000"
   environment:
     DATABASE_URL: postgres://user:user@postgres/user
     RUST_LOG: debug
   restart: always
   networks:
     - test
  locust:
    #image: ghcr.io/modulus/user-rust:latest
    build:
      context: locust
      dockerfile: Dockerfile
    container_name: locust
    ports:
      - "8000:8000" 
      - "2112:2112"   
    environment:
      HOST: "http://backend:8000"            
    restart: always
    networks:
      - test     
networks:
  test:
    driver: bridge