---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: demo
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/modulus/argocd-demo-app:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: web
          containerPort: 8000
        env: 
          - name: RUST_LOG
            value: info
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: demo
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8000
    name: web
    targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust
  namespace: demo
spec:
  selector:
    matchLabels:
      app: locust
  template:
    metadata:
      labels:
        app: locust
    spec:
      containers:
      - name: locust
        env: 
          - name: HOST
            value: "http://backend:8000"
        image: ghcr.io/modulus/argocd-demo-app-locust:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
